export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    AGENCY_SIGNUP: "/auth/agency/signup",
    AGENCY_LOGIN: "/auth/agency/login",
    ADMIN_LOGIN: "/auth/admin/login",
    SEND_OTP: "/auth/send-otp",
    RESEND_OTP: "/auth/resend-otp",
    VERIFY_OTP: "/auth/verify-otp",
    VERIFY_CREATE_USER: "/auth/verify-createuser",
    VERIFY_CREATE_AGENCY: "/auth/verify-create-agency",
    LOGOUT: "/auth/logout",
    REFRESH_TOKEN: "/auth/refresh-token",
    VERIFY_CARETAKER_INVITE: "/auth/verify-caretaker-invite",
    CARETAKER_SIGNUP: "/auth/caretaker/signup",
    CARETAKER_LOGIN: "/auth/caretaker/login",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    VERIFY_RESET_TOKEN: (token: string) => `/auth/verify-reset-token?token=${token}`,
    VERIFY_OLD_PASSWORD: "/auth/verify-old-password",
    CHANGE_PASSWORD: "/auth/change-password",
    AGENCY_REVERIFY: "/auth/agency/reverify",
    GOOGLE_AUTH: "/auth/google",
    ME: "/auth/me",
  },

  ADMIN: {
    USERS: "/admin/users",
    USER_DETAIL: (userId: string) => `/admin/users/${userId}`,
    USER_BLOCK: (userId: string) => `/admin/users/${userId}/block`,
    USER_UNBLOCK: (userId: string) => `/admin/users/${userId}/unblock`,
    AGENCIES: "/admin/agencies",
    AGENCY_DETAIL: (agencyId: string) => `/admin/agencies/${agencyId}`,
    AGENCY_BLOCK: (agencyId: string) => `/admin/agencies/${agencyId}/block`,
    AGENCY_UNBLOCK: (agencyId: string) => `/admin/agencies/${agencyId}/unblock`,
    AGENCY_VERIFY: (agencyId: string) => `/admin/agencies/${agencyId}/verify`,
    AGENCY_REJECT: (agencyId: string) => `/admin/agencies/${agencyId}/reject`,
    WALLET_TRANSACTIONS: "/admin/wallet-transactions",
    SALES_REPORT: "/admin/sales-report",
    SALES_REPORT_PDF: "/admin/sales-report/pdf",
    SALES_REPORT_EXCEL: "/admin/sales-report/excel",
  },

  AGENCY: {
    PROFILE: "/agency/profile",
    CARETAKERS_INVITE: "/agency/caretakers/invite",
    CARETAKERS_LIST: "/agency/caretakers",
    CARETAKER_STATUS: (caretakerId: string) => `/agency/caretakers/${caretakerId}/status`,
    CARETAKER_PRICE: (caretakerId: string) => `/agency/caretakers/${caretakerId}/price`,
    CARETAKER_DELETE: (caretakerId: string) => `/agency/caretakers/${caretakerId}`,
    CARETAKER_REQUESTS: "/agency/caretaker-requests",
    CARETAKER_REQUEST_FULFILL: (requestId: string) => `/agency/caretaker-requests/${requestId}/fulfill`,
    REFUND_REQUESTS: "/agency/refund-requests",
    REFUND_REQUEST_APPROVE: (requestId: string) => `/agency/refund-requests/${requestId}/approve`,
    REFUND_REQUEST_REJECT: (requestId: string) => `/agency/refund-requests/${requestId}/reject`,
    BOOKING_DETAIL: (bookingId: string) => `/agency/bookings/${bookingId}`,
    PACKAGES_BASE: "/agency/packages",
    PACKAGE_DETAIL: (packageId: string) => `/agency/packages/${packageId}`,
    PACKAGE_BOOKINGS: (packageId: string) => `/agency/packages/${packageId}/bookings`,
    PACKAGE_UPDATE: (packageId: string) => `/agency/packages/${packageId}`,
    PACKAGE_BASIC: (packageId: string) => `/agency/packages/${packageId}/basic`,
    PACKAGE_IMAGES: (packageId: string) => `/agency/packages/${packageId}/images`,
    PACKAGE_ITINERARY: (packageId: string) => `/agency/packages/${packageId}/itinerary`,
    PACKAGE_PUBLISH: (packageId: string) => `/agency/packages/${packageId}/publish`,
    PACKAGE_DELETE: (packageId: string) => `/agency/packages/${packageId}`,
    PACKAGE_COMPLETE: (packageId: string) => `/agency/packages/${packageId}/complete`,
    PACKAGE_CANCEL: (packageId: string) => `/agency/packages/${packageId}/cancel`,
    ACTIVITIES_BASE: "/agency/activities",
    UPLOAD_PROFILE_IMAGE: "/agency/upload/profile-image",
    UPLOAD_IMAGE: "/agency/upload/image",
    UPLOAD_IMAGES: "/agency/upload/images",
    SALES_REPORT: "/agency/sales-report",
    SALES_REPORT_PDF: "/agency/sales-report/pdf",
    SALES_REPORT_EXCEL: "/agency/sales-report/excel",
    REVIEWS: "/agency/reviews",
    REVIEWS_BY_PACKAGE: "/agency/reviews/by-package",
    CATEGORIES: "/agency/categories",
    CATEGORY_DETAIL: (id: string) => `/agency/categories/${id}`,
    CATEGORIES_ACTIVE: "/agency/categories/active",
    SPECIAL_NEEDS_MASTER: "/agency/special-needs-master",
    SPECIAL_NEEDS_MASTER_DETAIL: (id: string) => `/agency/special-needs-master/${id}`,
    SPECIAL_NEEDS_MASTER_ACTIVE: "/agency/special-needs-master/active",
    SPECIAL_NEEDS: "/agency/special-needs",
    SPECIAL_NEEDS_DETAIL: (id: string) => `/agency/special-needs/${id}`,
    SPECIAL_NEEDS_TOGGLE_ACTIVE: (id: string) => `/agency/special-needs/${id}/toggle-active`,
  },

  USER: {
    PROFILE: "/user/profile",
    UPLOAD_PROFILE_IMAGE: "/user/upload/profile-image",
    UPLOAD_DOCUMENTS: "/user/upload/documents",
    SIGNED_URL: "/user/signed-url",
    SIGNED_URLS: "/user/signed-urls",
    WISHLIST: "/user/wishlist",
    WISHLIST_DETAIL: (packageId: string) => `/user/wishlist/${packageId}`,
    WISHLIST_STATUS: (packageId: string) => `/user/wishlist/${packageId}/status`,
    AGENCY_REVIEWS: "/user/agency-reviews",
  },

  BOOKING: {
    CHECKOUT: "/booking/checkout",
    WALLET_PAY: "/booking/wallet-pay",
    PACKAGE_SPECIAL_NEEDS: (packageId: string) => `/booking/package/${packageId}/special-needs`,
    PRICE_PREVIEW: "/booking/price-preview",
    PACKAGE_CARETAKERS: (packageId: string) => `/booking/package/${packageId}/caretakers`,
    CONFIRM_SUCCESS: "/booking/confirm-success",
    CARETAKER_REQUEST: "/booking/caretaker-request",
    MY_BOOKINGS: "/booking/my",
    DETAIL: (bookingId: string) => `/booking/${bookingId}`,
    CANCEL: (bookingId: string) => `/booking/${bookingId}/cancel`,
    REFUND_REQUEST: (bookingId: string) => `/booking/${bookingId}/refund-request`,
  },

  PACKAGE: {
    PUBLIC_ROOT: "/packages",
    PUBLIC_UPCOMING: "/packages/upcoming",
    PUBLIC_CATEGORIES: "/packages/categories",
    DETAIL: (packageId: string) => `/packages/${packageId}`,
  },

  WALLET: {
    ME: "/wallets/me",
    ME_TRANSACTIONS: "/wallets/me/transactions",
    TOPUP_CHECKOUT: "/wallets/topup/checkout",
  },

  CARETAKER: {
    UPLOAD_DOCUMENTS: (folder?: string) =>
      folder ? `/caretaker/upload/documents?folder=${folder}` : "/caretaker/upload/documents",
    VERIFICATION: "/caretaker/verification",
    VERIFICATION_STATUS: "/caretaker/verification/status",
    PROFILE: "/caretaker/profile",
    DASHBOARD: "/caretaker/dashboard",
    TRIPS: "/caretaker/trips",
  },

  CHAT: {
    CONVERSATIONS: "/chat/conversations",
    BOOKING_MESSAGES: (bookingId: string) => `/chat/bookings/${bookingId}/messages`,
    ATTACHMENTS_UPLOAD: "/chat/attachments",
  },

  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: "/notifications/read-all",
  },
};
